services:
  - type: web
    name: nice-pasteis
    runtime: python
    plan: free
    healthCheckPath: /health/
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && python manage.py ensure_superuser && waitress-serve --url-scheme=https --port=$PORT core.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DJANGO_DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: nice-pasteis-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: INITIAL_SUPERUSER_USERNAME
        value: administrador
      - key: INITIAL_SUPERUSER_EMAIL
        value: administrador@localhost
      - key: INITIAL_SUPERUSER_PASSWORD
        sync: false
databases:
  - name: nice-pasteis-db
    plan: free
