# Generated by Django 5.2.15 on 2026-06-10 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('id_comanda', models.CharField(blank=True, max_length=20, unique=True)),
                ('mesa', models.PositiveIntegerField(blank=True, null=True)),
                ('cliente', models.CharField(blank=True, max_length=200)),
                ('obs', models.TextField(blank=True, help_text='Observações gerais da comanda')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada')], default='aberta', max_length=10)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('fechada_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comandas',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponivel', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='comandas.categoria')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('obs', models.CharField(blank=True, help_text='Ex: sem cebola, mal passado', max_length=300)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='comandas.comanda')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comandas.item')),
            ],
            options={
                'verbose_name': 'Item da Comanda',
                'verbose_name_plural': 'Itens da Comanda',
            },
        ),
    ]
